const mongoose = require('mongoose');

const mycourseSchema = new mongoose.Schema({
  allstudents: Number,
  students: Number,

  name: String,
  course: String,
  batches: Number,
  category:String,
  semail: String,
  sname: String,
  userid: String,
  catid: String,
  youcent: String,
  ccid:Number,
  amount:Number,
    aprofit:Number,
    tprofit:Number,
  students: Number,
  topics: Number,
  addedby: String,
  addedbyid: String,
  addedbytype: String,
  cid: String,
  intro: String,
  introlink: String,
  desc: String,
  teacher: String,
  teacherid: String,
  profit: Number,
  topics: Number,

  editedby: String,
  lastedit: String,
  lasteditby: String,
  lastedittime: String,
  timesedited: Number,
  leads: Number,
  durationm: String,
  duration: Number,
  expiredstudents: Number,
  preexpiredstudents: Number,
  dprofit: String,
  tid: String,
  teacherid: String,
  mandystudents: Number,
  mstudents: Number,
  rev: Number,
  mrev: Number,
  drev: String,
  mdrev: String,
  mandyleads: Number,
  image: String,
  draw: String,
  price: Number,
  attendance: Number,
  dprice: String,
  ordstring: Date,
  created: Date,
  createddate: String,
  lastpaid: String,
  sn: Number,
  deployed: Boolean,
  locked: Boolean,
  rating:{type:Number,default:3},
  reviews:{type:Number,default:500},
});

module.exports = new mongoose.model('mycourse', mycourseSchema);
